language: node_js
node_js: node
env:
  secure: BDiZA4i/3yy5tOeDAY/R1Lwv8BIV9u75kQRESvTq/ec8wHz5uHidfw2ov4qvhZdfiVnv78S034moipwT8GlShYm1ZVWANOITFKSYvniCdLG5u5Bfwuk6QsneVer1f3Ye5lfrJH8st1V6hyK8wzCNbT+gSsUkr6pvBrtN/o94Tw0uuVjae+UusWepkVFv6mTKMexWwB+89nyn6/Q2ThgREz+6X1Ka17SisrLlbhE/2RK9UJxXjaoIljsKw2cs2GFcUYnlvOLFSQdBNpQ0hC/1QVqYP9MKok4o9ZeHx+TscQ3VaseyqcyoORhm7efchkflNhMwYOZTXpF7KMuukfjir07+S2e+j1Wb2jkler9SAAjA/SJlOp323an3mD8SCiHNncUs0bs12u7BBWwvnLTRMNxEK6GM/De7lH5wrZ8e8yzWSFMaQ0C3uEes8omUTm6eFHAFMGd/dQRwKeEu6bm+vhFBvH2NJmVNaTU6ESBSPdH5AqsiLMFNa9AQFBV6FxJS4jSF56qpxX/7jv+FKsLO6iKv6qalLNO4J7M6KBKhcWfPl2UnI+SqEEef694SoG4KWUntk1LT7curOTc35gRjVrC9GigFr9UQMzy/9o4vGD1rzud8ElGtNRij4Xd8gkTttXevPcl2jBdA/f3ZLNSozXZ04RsKbLQ68LOpD3i1MHE=
cache:
  directories:
    - node_modules

script: npm run build
before_deploy:
- curl --location --retry 5 --output ossutil 'https://github.com/mycard/ossutil/releases/download/1.0.0.Beta2/ossutil'
- chmod +x ossutil
- ./ossutil config --endpoint oss-cn-hangzhou.aliyuncs.com --access-key-id $ALIYUN_ID
  --access-key-secret $ALIYUN_SECRET
deploy:
  provider: script
  script: ./ossutil cp -rf dist oss://mycard/mobile2
  skip_cleanup: true
  on:
    branch: master
